In [4]:
import pandas as pd

## Accessing Data

In [19]:
cofee = pd.read_csv("Data/coffee.csv")

In [28]:
cofee.shape

(14, 3)

In [20]:
cofee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

## Learning loc

In [33]:
cofee.loc[[0,2,5],["Units Sold", "Day"]]

   Units Sold        Day
0          25     Monday
2          30    Tuesday
5          25  Wednesday

In [34]:
cofee.loc[0, "Coffee Type"]

'Espresso'

In [41]:
cofee.loc[(cofee["Units Sold"]>30) & (cofee["Day"] == "Saturday") ]

         Day Coffee Type  Units Sold
10  Saturday    Espresso          45
11  Saturday       Latte          35

In [42]:
cofee.loc[0, "Units Sold"] = 20

In [43]:
cofee

          Day Coffee Type  Units Sold
0      Monday    Espresso          20
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

## Learning iloc

In [46]:
cofee.iloc[0 ,2]

20

In [47]:
cofee.iloc[0:10:2]

         Day Coffee Type  Units Sold
0     Monday    Espresso          20
2    Tuesday    Espresso          30
4  Wednesday    Espresso          35
6   Thursday    Espresso          40
8     Friday    Espresso          45

## Learning Query

In [11]:
pokemon_data = pd.read_csv("Data/Pokemon.csv", index_col="Name")

pokemon = input ("Enter the name of the Pokemon")

try:
    print(pokemon_data.loc[pokemon])
except KeyError:
    print(f" {pokemon} is not found")

No                 25
Type1        Electric
Type2             NaN
Height            0.4
Weight            6.0
Legendary           0
Name: Pikachu, dtype: object

In [10]:
pokemon_data.head

<bound method NDFrame.head of       No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire     NaN     0.6     8.5          0
4      5  Charmeleon     Fire     NaN     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon     NaN     1.8     3.3          0
147  148   Dragonair   Dragon     NaN     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 7 columns]>

## Finding Water Pokemon

In [14]:
water_pokemon = pokemon_data[(pokemon_data['Type1']== 'Water') | (pokemon_data['Type2']== 'Water')]

print(water_pokemon)

             No  Type1     Type2  Height  Weight  Legendary
Name
Squirtle      7  Water       NaN     0.5     9.0          0
Wartortle     8  Water       NaN     1.0    22.5          0
Blastoise     9  Water       NaN     1.6    85.5          0
Psyduck      54  Water       NaN     0.8    19.6          0
Golduck      55  Water       NaN     1.7    76.6          0
Poliwag      60  Water       NaN     0.6    12.4          0
Poliwhirl    61  Water       NaN     1.0    20.0          0
Poliwrath    62  Water  Fighting     1.3    54.0          0
Tentacool    72  Water    Poison     0.9    45.5          0
Tentacruel   73  Water    Poison     1.6    55.0          0
Slowpoke     79  Water   Psychic     1.2    36.0          0
Slowbro      80  Water   Psychic     1.6    78.5          0
Seel         86  Water       NaN     1.1    90.0          0
Dewgong      87  Water       Ice     1.7   120.0          0
Shellder     90  Water       NaN     0.3     4.0          0
Cloyster     91  Water       Ice     1.5   132.5          0
Krabby       98  Water       NaN     0.4     6.5          0
Kingler      99  Water       NaN     1.3    60.0          0
Horsea      116  Water       NaN     0.4     8.0          0
Seadra      117  Water       NaN     1.2    25.0          0
Goldeen     118  Water       NaN     0.6    15.0          0
Seaking     119  Water       NaN     1.3    39.0          0
Staryu      120  Water       NaN     0.8    34.5          0
Starmie     121  Water   Psychic     1.1    80.0          0
Magikarp    129  Water       NaN     0.9    10.0          0
Gyarados    130  Water    Flying     6.5   235.0          0
Lapras      131  Water       Ice     2.5   220.0          0
Vaporeon    134  Water       NaN     1.0    29.0          0
Omanyte     138   Rock     Water     0.4     7.5          0
Omastar     139   Rock     Water     1.0    35.0          0
Kabuto      140   Rock     Water     0.5    11.5          0
Kabutops    141   Rock     Water     1.3    40.5          0